name: Build & Push Docker image
on:
  push:
    branches:
      - feat/dockerfile
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          dockerfile: PostMicroservice/Dockerfile
          directory: PostMicroservice
          image: post-microservice
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}